# Global Configuration

privatemines:
  enabled: true
  world: privatemines # The world where all private mines are stored

# Tax Module
tax:
  enabled: true # If this is disabled, users will not be allowed to claim tax
  max-tax-rate: 50 # A mine can't have more than 50% tax
  min-tax-rate: 0 # Minimum tax rate for a mine

# Global Tax Module
# This is a tax rate that is applied to every mine
global-tax:
  enabled: true
  rate: 5.0
  # How the global tax rate should combine with mine-specific tax, if applicable
  # COMBINE - Combine the global tax rate and the mine's tax rate
  # OVERRIDE - The mine's tax rate overrides the global tax rate
  # IGNORE - The global tax rate overrides the mine's tax rate
  method: OVERRIDE
